export const paths = {
  home: "/",
  dashboard: "/dashboard",
  permintaan: "/permintaan",
  reservasi: "/reservasi",
  reservasiCreate: "/reservasi/create",
  penyewaan: "/penyewaan",
  penyewaanWalkIn: "/penyewaan/walk-in",
  pengembalian: "/pengembalian",
  inventaris: "/inventaris",
  inventarisCreate: "/inventaris/create",
  inventarisLocations: "/inventaris/lokasi",
  pemeriksaan: "/pemeriksaan",
  perawatan: "/perawatan",
  penyewa: "/penyewa",
  katalog: "/katalog",
  katalogEdit: "/katalog/edit",
  katalogManage: "/katalog/manage",
  pemasok: "/pemasok",
  pemasokCreate: "/pemasok/create",
  pembelian: "/pembelian",
  pembelianCreate: "/pembelian/create",
  keuangan: "/keuangan",
  pemberitahuan: "/pemberitahuan",
  laporan: "/laporan",
  qrUnit: "/qr/unit",
  qrPenyewaan: "/qr/penyewaan",
} as const;

export type AppPath = (typeof paths)[keyof typeof paths];
